### ISSUE TITLE
"Trying to access array offset on value of type null" on PHP 7.4 

### ISSUE THREAD

**Issue by jdousdebes** [mercadopago/sdk-php#247]
After updating PHP from 7.3 to 7.4, I got the following error:
_"Trying to access array offset on value of type null"_

After some time debugging, I've found the line that's being problematic:
`$ payment = new MercadoPago \ Payment ();`

That's the blessed line that throws error.

1. Use php 7.4.
2. Use version 1.8 of this package.
3. Receive a cc payment.

I've managed to solve this problem by downgrading php to 7.3, but that's not ideal.

**Comment by agustinz97** [comment]
I am having the same problem with PHP 7.4.3 when creating an Item or a Preference for Checkout.

Error lines:
`$item = new MercadoPago\Item();`
`$preference = new MercadoPago\Preference();`

Any solution yet?

**Comment by byinff** [comment]
Jajajjaja, I am having this same issue. When I created an example payment.

**Comment by byinff** [comment]
Log information 

[2020-03-21 23:32:59] local.ERROR: ErrorException: Trying to access array offset on value of type null in /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:995
Stack trace:
#0 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(995): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#1 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(687): Doctrine\Common\Annotations\DocParser->Identifier()
#2 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#3 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#4 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(250): Doctrine\Common\Annotations\DocParser->parse()
#5 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/MetaDataReader.php(55): Doctrine\Common\Annotations\AnnotationReader->getPropertyAnnotations()
#6 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/MetaDataReader.php(46): MercadoPago\MetaDataReader->getMetaData()
#7 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(50): MercadoPago\MetaDataReader->getMetaData()
#8 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(176): MercadoPago\Manager->_getEntityConfiguration()
#9 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(40): MercadoPago\Manager->setEntityMetadata()
#10 /var/www/example-app/app/Services/v1/PaymentService.php(21): MercadoPago\Entity->__construct()
#11 /var/www/example-app/app/Repositories/v1/Activity/ActivityRepository.php(86): App\Services\v1\PaymentService->pay()
#12 /var/www/example-app/app/Http/Controllers/v1/ActivityController.php(48): App\Repositories\v1\Activity\ActivityRepository::pay()
#13 [internal function]: App\Http\Controllers\v1\Activity\ActivityController->pay()
#14 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array()
#15 /var/www/example-app/vendor/illuminate/container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#17 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /var/www/example-app/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#19 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Illuminate\Container\Container->call()
#20 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(342): Laravel\Lumen\Application->callControllerCallable()
#21 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(316): Laravel\Lumen\Application->callLumenController()
#22 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(278): Laravel\Lumen\Application->callControllerAction()
#23 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(258): Laravel\Lumen\Application->callActionOnArrayBasedRoute()
#24 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#25 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): call_user_func()
#26 /var/www/example-app/app/Http/Middlewares/v1/IsAuthenticatedMiddleware.php(20): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}()
#27 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middlewares\v1\IsAuthenticatedMiddleware->handle()
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): call_user_func()
#30 /var/www/example-app/app/Http/Middlewares/v1/ThrottleRequestsMiddleware.php(48): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}()
#31 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middlewares\v1\ThrottleRequestsMiddleware->handle()
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): call_user_func()
#34 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}()
#35 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\Pipeline\Pipeline->then()
#36 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(259): Laravel\Lumen\Application->sendThroughPipeline()
#37 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(233): Laravel\Lumen\Application->handleFoundRoute()
#38 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(169): Laravel\Lumen\Application->handleDispatcherResponse()
#39 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(416): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#40 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\Lumen\Application->sendThroughPipeline()
#41 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\Lumen\Application->dispatch()
#42 /var/www/example-app/public/index.php(28): Laravel\Lumen\Application->run()
#43 {main} {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:995)
[stacktrace]
#0 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(995): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#1 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(687): Doctrine\\Common\\Annotations\\DocParser->Identifier()
#2 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\\Common\\Annotations\\DocParser->Annotation()
#3 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\\Common\\Annotations\\DocParser->Annotations()
#4 /var/www/example-app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(250): Doctrine\\Common\\Annotations\\DocParser->parse()
#5 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/MetaDataReader.php(55): Doctrine\\Common\\Annotations\\AnnotationReader->getPropertyAnnotations()
#6 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/MetaDataReader.php(46): MercadoPago\\MetaDataReader->getMetaData()
#7 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(50): MercadoPago\\MetaDataReader->getMetaData()
#8 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(176): MercadoPago\\Manager->_getEntityConfiguration()
#9 /var/www/example-app/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php(40): MercadoPago\\Manager->setEntityMetadata()
#10 /var/www/example-app/app/Services/v1/PaymentService.php(21): MercadoPago\\Entity->__construct()
#11 /var/www/example-app/app/Repositories/v1/Activity/ActivityRepository.php(86): App\\Services\\v1\\PaymentService->pay()
#12 /var/www/example-app/app/Http/Controllers/v1/ActivityController.php(48): App\\Repositories\\v1\\Activity\\ActivityRepository::pay()
#13 [internal function]: App\\Http\\Controllers\\v1\\Activity\\ActivityController->pay()
#14 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array()
#15 /var/www/example-app/vendor/illuminate/container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /var/www/example-app/vendor/illuminate/container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/example-app/vendor/illuminate/container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Illuminate\\Container\\Container->call()
#20 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(342): Laravel\\Lumen\\Application->callControllerCallable()
#21 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(316): Laravel\\Lumen\\Application->callLumenController()
#22 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(278): Laravel\\Lumen\\Application->callControllerAction()
#23 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(258): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute()
#24 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#25 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): call_user_func()
#26 /var/www/example-app/app/Http/Middlewares/v1/IsAuthenticatedMiddleware.php(20): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}()
#27 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(167): App\\Http\\Middlewares\\v1\\IsAuthenticatedMiddleware->handle()
#28 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): call_user_func()
#30 /var/www/example-app/app/Http/Middlewares/v1/ThrottleRequestsMiddleware.php(48): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}()
#31 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(167): App\\Http\\Middlewares\\v1\\ThrottleRequestsMiddleware->handle()
#32 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/example-app/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): call_user_func()
#34 /var/www/example-app/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}()
#35 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(259): Laravel\\Lumen\\Application->sendThroughPipeline()
#37 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(233): Laravel\\Lumen\\Application->handleFoundRoute()
#38 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(169): Laravel\\Lumen\\Application->handleDispatcherResponse()
#39 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(416): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#40 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->sendThroughPipeline()
#41 /var/www/example-app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch()
#42 /var/www/example-app/public/index.php(28): Laravel\\Lumen\\Application->run()
#43 {main}
"}

**Comment by byinff** [comment]
https://github.com/mercadopago/dx-php/issues/226
